config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get "about/index"
  get "home/index"
  get "types/index"
  get "types/show"
  get "players/index"
  get "players/show"
  get "pokemons/index"
  get "pokemons/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "about" => "about#index"
  get "about" => "pages#about", as: "about"
  root to: "home#index"
  resources :pokemons, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :players, only: %i[index show]
  resources :types, only: %i[index show]
end

app/models/address.rb
class Address < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :player_pokemons
  has_many :pokemons, through: :player_pokemons
  validates :name, presence: true, uniqueness: true
  paginates_per 20
end

app/models/player_pokemon.rb
class PlayerPokemon < ApplicationRecord
  belongs_to :player
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :type
  has_many :player_pokemons
  has_many :players, through: :player_pokemons
  paginates_per 20
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemons
  validates :name, presence: true, uniqueness: true
  paginates_per 20
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @types = Type.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pokemons = Pokemon.order("stat_total DESC")
                       .limit(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.order(:name).page(params[:page])
  end

  def show
    @player = Player.find(params[:id])
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.order(:name).page(params[:page])
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @pokemons = Pokemon.where("name LIKE ?", wildcard_search)
                       .where("type_id == #{params[:id]}")
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end

  def show
    @type = Type.find(params[:id])
    @pokemons = @type.pokemons.order(:name).page(params[:page])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top 10 Pokemons</h2>

        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th>Name</th>
            <th>Stat Total</th>
            <th>HP</th>
            <th>Attack</th>
            <th>Defense</th>
            <th>Speed</th>
            <th>First Ability</th>
            <th>Seconde Ability</th>
            <th>Hidden Ability</th>
          </tr>
        </thead>
        <tbody>
          <% @pokemons.each do |pokemon| %>
            <tr>
              <td><%= link_to pokemon.name, pokemon %></td>
              <td><%= pokemon.stat_total %></td>
              <td><%= pokemon.HP %></td>
              <td><%= pokemon.attack %></td>
              <td><%= pokemon.defense %></td>
              <td><%= pokemon.speed %></td>
              <td><%= pokemon.first_ability %></td>
              <td><%= pokemon.second_ability %></td>
              <td><%= pokemon.hidden_ability %></td>
            </tr>
          <% end %>
        </tbody>
</table>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Home of Pokemons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
  </head>

  <body>
    <section class="container">
      <div style= "display: flex; flex: 1; justify-content: center; margin: 0;">
        <h1 class="panel-heading title is-1 has-text-link">Home of Pokemons</h1>
      </div>
      <%= render partial:'shared/navbar'%>
      <%= form_with(url: search_pokemons_path, method: :get, local: true) do %>
        <div class="field is-grouped mb-5">
          <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search for pokemons...") %>
        </div>
        <div>
          <%= select_tag(:id, options_from_collection_for_select(Type.all, :id, :name)) %>
        </div>
        <div class="control">
          <%= submit_tag("search", class: "button is-primary") %>
        </div>
      <% end %>
      <%= yield %>
    </section>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="title is-4">This is a dataset about Pokemon and players</h1>
<p>All the data about pokemon is pulled from a CSV file called Pokemon_Data.csv, and it will be divided into four tables.
the data about players is created by faker.</p>
<p>Pokemons and Types tables are from pokemon.</p>
<p>Players table is from faker.</p>
<p>The player_pokemons table is a bridge table between pokemons and players.</p>

<h1>https://github.com/MrZhipeng/Rails_Intro_Project.git</h1>

<p>pokemons</p>
<p> -id, name, type_id, total, HP, attack, defense, speed, first_ability, second_ability, hidden_ability</p>
<p>types</p>
<p> -id, name</p>
<p>players</p>
<p> -id, name</p>
<p>player_pokemons</p>
<p> -player_id, pokemon_id</p>
<%=link_to "Go Back", :back%>

app/views/players/index.html.erb
<h1 style="display: flex; flex: 1; justify-content: center; margin: 0;">Players</h1>
<div style="display: flex; flex: 1; justify-content: center;">
  <ul>
    <% @players.each do |player| %>
      <li>
      <%= link_to player.name, player %>
      </li>
    <% end %>
  </ul>
</div>

<div class= "p-4 has-background-link-light m-4" style="width:60%;">
  <%= paginate @players %>
</div>

<%=link_to "Go Back", :back%>

app/views/players/show.html.erb
<% content_for(:html_title) {@player.name}%>
<h1 class="title is-1" style="display: flex; flex: 1; justify-content: center; margin: 0;">
  <%= @player.name %>
</h1>

<div class="title is-3" style="display: flex; flex: 1; justify-content: center; margin: 0;">
  <% if @player.pokemons.count > 0 %>
    <h2>
      The player has <%= @player.pokemons.count %> pokemons.
    </h2>
  <% else %>
    <h2>
      The player has no pokemon.
    </h2>
  <% end %>
</div>

<div style="display: flex; flex: 1; justify-content: center;">
  <ul>
    <% @player.pokemons.each do |pokemon| %>
      <li><%= link_to pokemon.name, pokemon %></li>
    <% end %>
  </ul>
</div>

<%=link_to "Go Back", :back%>

app/views/pokemons/index.html.erb
<h1 style="display: flex; flex: 1; justify-content: center; margin: 0;">Pokemons</h1>
<div style="display: flex; flex: 1; justify-content: center;">
  <ul>
    <% @pokemons.each do |pokemon| %>
      <li>
      <%= link_to pokemon.name, pokemon %>
      </li>
    <% end %>
  </ul>
</div>

<div class= "p-4 has-background-link-light m-4" style="width:60%;">
  <%= paginate @pokemons %>
</div>
<%=link_to "Go Back", :back%>

app/views/pokemons/search.html.erb
<p class="mb-5">
  Pokemons found when searching for: <%= params[:keywords] %>
</p>

<ul>
  <% @pokemons.each do |pokemon| %>
    <li><%= link_to pokemon.name, pokemon %></li>
  <% end %>
</ul>
<%=link_to "Go Back", :back%>

app/views/pokemons/show.html.erb
<% content_for(:html_title) {@pokemon.name}%>
<h1 style="display: flex; flex: 1; justify-content: center; margin: 0;"><%= @pokemon.name %></h1>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <tr>
    <th>Type</th>
    <td><%= link_to @pokemon.type.name, @pokemon.type %></td>
  </tr>
  <tr>
    <th>Stat Total</th>
    <td><%= @pokemon.stat_total %></td>
  </tr>
  <tr>
    <th>HP</th>
    <td><%= @pokemon.HP %></td>
  </tr>
  <tr>
    <th>Attack</th>
    <td><%= @pokemon.attack %></td>
  </tr>
  <tr>
    <th>Defense</th>
    <td><%= @pokemon.defense %></td>
  </tr>
  <tr>
    <th>Speed</th>
    <td><%= @pokemon.speed %></td>
  </tr>
  <tr>
    <th>First Ability</th>
    <td><%= @pokemon.first_ability %></td>
  </tr>
  <tr>
    <th>Second Ability</th>
    <td><%= @pokemon.second_ability %></td>
  </tr>
  <tr>
    <th>Hidden Ability</th>
    <td><%= @pokemon.hidden_ability %></td>
  </tr>
</table>

<div style="display: flex; flex: 1; justify-content: center;">
  <% if @pokemon.players.count > 1 %>
    <h2> There are <%= @pokemon.players.count %> Players who have <%= @pokemon.name %>. See the list:</h2>
  <% elsif @pokemon.players.count == 1 %>
      <h2> There are 1 Player who have <%= @pokemon.name %>. See the name:</h2>
  <% else %>
    <h2>No player has <%= @pokemon.name %>.</h2>
  <% end %>
</div>
<div style="display: flex; flex: 1; justify-content: center;">
  <ul>
    <% @pokemon.players.each do |player| %>
    <li><%= link_to player.name, player %></li>
    <% end %>
  </ul>
</div>

<%=link_to "Go Back", :back%>

app/views/shared/_navbar.html.erb
<div class="navbar-container has-background-warning-light" style="display: flex; justify-content: center;" >
  <nav class="navbar has-background-warning-light" role="navigation" aria-label="main navigation">
      <div class="navbar-start">
        <div class="navbar-item">
          <%= link_to "Home", root_path %>
        </div>
        <div class="navbar-item">
          <%= link_to "Players", players_path %>
        </div>
        <div class="navbar-item">
          <%= link_to "Pokemons", pokemons_path %>
        </div>
        <div class="navbar-item">
          <%= link_to "Types", types_path %>
        </div>
        <div class="navbar-item">
          <%= link_to "About", about_path %>
        </div>
      </div>
  </nav>
</div>

app/views/types/index.html.erb
<h1 class="title is-3" style="display: flex; flex: 1; justify-content: center;">Types</h1>
<div style="display: flex; flex: 1; justify-content: center;">
  <ul>
    <% @types.each do |type| %>
      <li>
      <%= link_to type.name, type %>
      </li>
    <% end %>
  </ul>
</div>
<%=link_to "Go Back", :back%>

app/views/types/show.html.erb
<% content_for(:html_title) {@type.name}%>
<h1 style="display: flex; flex: 1; justify-content: center; margin: 0;"><%= @type.name %></h1>

<div style="display: flex; flex: 1; justify-content: center;">
  <ul>
    <% @pokemons.each do |pokemon| %>
      <li>
      <%= link_to pokemon.name, pokemon %>
      </li>
    <% end %>
  </ul>
</div>

<div class= "p-4 has-background-link-light m-4" style="width:60%;">
  <%= paginate @pokemons %>
</div>
<%=link_to "Go Back", :back%>